import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const ABCCameraFont = localFont({
  src: './fonts/ABCCameraPlainVariable-Trial.ttf',
})



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ABCCameraFont.className}>{children}</body>
    </html>
  )
}
